#!/bin/sh

[ $TERM = "screen" ] && fzf=fzf || fzf=fzf-tmux

container=`docker ps --format "{{.Names}}" | $fzf --reverse --exit-0 --select-1 --tac`

if [ -n "$container" ]; then
    docker exec -it $container /bin/bash
else
    echo Error: Don\'t have any containers.
fi
